### ISSUE TITLE
Is it working on Mysql ?

### ISSUE THREAD

**Issue by wbspool** [aaronhagopian/springboot-gorm-demo#1]
I tried with the config of  `http://gorm.grails.org/6.0.x/hibernate/manual/` ,but it doesn't work !

**Comment by aaronhagopian** [comment]
I made some changes since GORM 6.0.4 came out which fixed all the issues I was having so it should be working now. I left in the commented out settings in application.yml for working with MySQL for you and just comment out the h2 driver and uncomment the mysql driver in build.gradle and it should work for you now.
